# Generated by Django 4.2.7 on 2023-11-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.position')),
            ],
        ),
    ]
